-- ════════════════════════════════════════════════════════════════════════════
-- FastBuy — one-time Postgres provisioning (run once in Neon's SQL editor).
--
-- Differences vs the H2 dev scripts (src/main/resources/schema.sql + data.sql):
--   • AUTO_INCREMENT          → BIGINT GENERATED BY DEFAULT AS IDENTITY
--   • DOUBLE                  → DOUBLE PRECISION
--   • DATEADD(...)            → NOW() + INTERVAL '...'
--   • live events get a wide window so the demo stays "live" on a persistent DB
--   • NO demo orders are seeded (orders start empty; IDENTITY starts at 1)
--   • NO bartender_users here — DataInitializer seeds them (BCrypt) on first boot
-- ════════════════════════════════════════════════════════════════════════════

-- ── Schema ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS categories (
    id    VARCHAR(50)  NOT NULL PRIMARY KEY,
    label VARCHAR(100) NOT NULL,
    emoji VARCHAR(10)  NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id        VARCHAR(50)  NOT NULL PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    venue     VARCHAR(255) NOT NULL,
    hours     VARCHAR(100) NOT NULL,
    starts_at TIMESTAMP    NOT NULL,
    ends_at   TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS bars (
    id       VARCHAR(50)  NOT NULL PRIMARY KEY,
    label    VARCHAR(100) NOT NULL,
    location VARCHAR(255) NOT NULL,
    event_id VARCHAR(50)  NOT NULL,
    FOREIGN KEY (event_id) REFERENCES events(id)
);

CREATE TABLE IF NOT EXISTS products (
    id       VARCHAR(50)      NOT NULL PRIMARY KEY,
    name     VARCHAR(255)     NOT NULL,
    category VARCHAR(50)      NOT NULL,
    price    DOUBLE PRECISION NOT NULL,
    stock    INT              NOT NULL,
    image    VARCHAR(255),
    emoji    VARCHAR(16),
    subtitle VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS bar_products (
    bar_id     VARCHAR(50) NOT NULL,
    product_id VARCHAR(50) NOT NULL,
    PRIMARY KEY (bar_id, product_id),
    FOREIGN KEY (bar_id)     REFERENCES bars(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS orders (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total      DOUBLE PRECISION NOT NULL,
    items      VARCHAR(2000)    NOT NULL,
    status     VARCHAR(20)      NOT NULL,
    bar        VARCHAR(50)      NOT NULL,
    time       VARCHAR(10)      NOT NULL,
    item_count INT              NOT NULL DEFAULT 0,
    claimed_by VARCHAR(100),
    claimed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bartender_users (
    id            VARCHAR(50)  NOT NULL PRIMARY KEY,
    username      VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    bar_id        VARCHAR(50)  NOT NULL,
    session_token VARCHAR(100),
    FOREIGN KEY (bar_id) REFERENCES bars(id)
);

CREATE TABLE IF NOT EXISTS admin_users (
    id            VARCHAR(50)  NOT NULL PRIMARY KEY,
    username      VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    event_id      VARCHAR(50)  NOT NULL,
    session_token VARCHAR(100),
    FOREIGN KEY (event_id) REFERENCES events(id)
);

CREATE TABLE IF NOT EXISTS payment_accounts (
    id            VARCHAR(50)  NOT NULL PRIMARY KEY,
    event_id      VARCHAR(50)  NOT NULL UNIQUE,
    mp_user_id    VARCHAR(100),
    access_token  VARCHAR(512) NOT NULL,
    refresh_token VARCHAR(512),
    expires_at    TIMESTAMP,
    linked_at     TIMESTAMP    NOT NULL,
    FOREIGN KEY (event_id) REFERENCES events(id)
);

-- ── Catalog seed ──────────────────────────────────────────────────────────────
-- Categories
INSERT INTO categories (id, label, emoji) VALUES
    ('drink', 'Bebidas', '🍺'),
    ('snack', 'Snacks',  '🍟'),
    ('food',  'Comida',  '🌭'),
    ('all',   'Todos',   '🍽️')
ON CONFLICT (id) DO NOTHING;

-- Events are anchored relative to NOW() so the seeded lineup classifies
-- dynamically: e1/e2 run from earlier today into tonight (LIVE), e3 is
-- tomorrow, e5 far-future. On a persistent DB these drift over time —
-- re-run deploy/reset-total.sql to re-anchor them to "today" before a demo.
INSERT INTO events (id, name, venue, hours, starts_at, ends_at) VALUES
    ('e1', 'Festival Eclipse',            'Costanera Sur · CABA',    '21:00 - 04:00', NOW() - INTERVAL '6 hours',  NOW() + INTERVAL '12 hours'),
    ('e2', 'Festival Cumbiero',           'Parque Sarmiento · CABA', '20:00 - 03:00', NOW() - INTERVAL '3 hours',  NOW() + INTERVAL '9 hours'),
    ('e3', 'Cosquín Rock',                'Cosquín · Córdoba',       '18:00 - 02:00', NOW() + INTERVAL '1 day',    NOW() + INTERVAL '2 days'),
    ('e5', 'Lollapalooza Argentina 2027', 'Hipódromo de Palermo',    '14:00 - 23:00', NOW() + INTERVAL '300 days', NOW() + INTERVAL '303 days')
ON CONFLICT (id) DO NOTHING;

-- Bars
INSERT INTO bars (id, label, location, event_id) VALUES
    ('eclipse-north',  'Barra Norte',   'Sector Norte · Entrada Principal',        'e1'),
    ('eclipse-center', 'Barra Central', 'Centro del Predio · cerca del escenario', 'e1'),
    ('eclipse-south',  'Barra Sur VIP', 'Sector Sur · Zona VIP',                   'e1'),
    ('cumbia-main',    'Barra Principal','Patio Central · Frente al Escenario',    'e2'),
    ('cumbia-vip',     'Barra VIP',     'Sector Dorado · Acceso Exclusivo',        'e2')
ON CONFLICT (id) DO NOTHING;

-- Products (p1–p23). p_test is a dev-only artifact and is intentionally omitted.
INSERT INTO products (id, name, category, price, stock, image, emoji, subtitle) VALUES
    ('p1',  'Carlsberg 500ml',        'drink', 8000,  50,  '🍺', '🍺', 'Lata · 500 ml'),
    ('p2',  'Heineken 500ml',         'drink', 8500,  45,  '🍻', '🍻', 'Lata · 500 ml'),
    ('p3',  'Corona Extra 355ml',     'drink', 7000,  60,  '🌴', '🌴', 'Porrón · 355 ml'),
    ('p4',  'Stella Artois 500ml',    'drink', 9000,  40,  '🌟', '🌟', 'Pinta · 500 ml'),
    ('p5',  'Agua mineral 500ml',     'drink', 2500,  100, '💧', '💧', 'Botella · 500 ml'),
    ('p6',  'Coca-Cola 500ml',        'drink', 3000,  80,  '🥤', '🥤', 'Lata · 500 ml'),
    ('p7',  'Sprite 500ml',           'drink', 3000,  75,  '🍋', '🍋', 'Lata · 500 ml'),
    ('p8',  'Nachos con salsa',       'snack', 5000,  30,  '🌮', '🌮', 'Porción individual'),
    ('p9',  'Papas fritas',           'snack', 4500,  35,  '🍟', '🍟', 'Porción individual'),
    ('p10', 'Mini pizza',             'food',  7500,  20,  '🍕', '🍕', 'Muzzarella · 4 porciones'),
    ('p11', 'Chorizo a la parrilla',  'food',  9000,  15,  '🌭', '🌭', 'Pan + chimichurri'),
    ('p12', 'Panchos con cheddar',    'food',  6500,  25,  '🧀', '🧀', 'Doble cheddar'),
    ('p13', 'Empanadas x3',           'food',  8000,  30,  '🥟', '🥟', 'Surtido · 3 unidades'),
    ('p14', 'Champagne Premium',      'drink', 18000, 10,  '🍾', '🍾', 'Copa · sólo VIP'),
    ('p15', 'Whisky Premium',         'drink', 15000, 12,  '🥃', '🥃', 'Vaso · sólo VIP'),
    ('p16', 'Fernet con Coca',        'drink', 5500,  60,  '🫗', '🫗', 'Vaso largo · 400 ml'),
    ('p17', 'Malbec Copa',            'drink', 6500,  40,  '🍷', '🍷', 'Copa · 200 ml'),
    ('p18', 'Sangría 500ml',          'drink', 5000,  50,  '🍹', '🍹', 'Vaso · 500 ml'),
    ('p19', 'IPA Artesanal 500ml',    'drink', 9500,  30,  '🫙', '🫙', 'Lata · 500 ml'),
    ('p20', 'Agua mineral 500ml',     'drink', 2500,  100, '💧', '💧', 'Botella · 500 ml'),
    ('p21', 'Provoleta a la parrilla','food',  10500, 20,  '🧆', '🧆', 'Con aceite y orégano'),
    ('p22', 'Choripán',               'food',  9000,  25,  '🥖', '🥖', 'Pan brioche + chimichurri'),
    ('p23', 'Tabla de fiambres',      'snack', 14000, 15,  '🪵', '🪵', '2 personas · surtida')
ON CONFLICT (id) DO NOTHING;

-- Bar ↔ product menus (p_test rows omitted)
INSERT INTO bar_products (bar_id, product_id) VALUES
    ('eclipse-north', 'p1'), ('eclipse-north', 'p2'), ('eclipse-north', 'p3'),
    ('eclipse-north', 'p5'), ('eclipse-north', 'p6'), ('eclipse-north', 'p7'),
    ('eclipse-north', 'p8'), ('eclipse-north', 'p9'), ('eclipse-north', 'p11'),
    ('eclipse-north', 'p12'), ('eclipse-north', 'p13'),
    ('eclipse-center', 'p1'), ('eclipse-center', 'p2'), ('eclipse-center', 'p4'),
    ('eclipse-center', 'p5'), ('eclipse-center', 'p6'), ('eclipse-center', 'p8'),
    ('eclipse-center', 'p9'), ('eclipse-center', 'p10'), ('eclipse-center', 'p12'),
    ('eclipse-center', 'p13'),
    ('eclipse-south', 'p2'), ('eclipse-south', 'p4'), ('eclipse-south', 'p5'),
    ('eclipse-south', 'p6'), ('eclipse-south', 'p10'), ('eclipse-south', 'p13'),
    ('eclipse-south', 'p14'), ('eclipse-south', 'p15'),
    ('cumbia-main', 'p16'), ('cumbia-main', 'p17'), ('cumbia-main', 'p18'),
    ('cumbia-main', 'p20'), ('cumbia-main', 'p21'), ('cumbia-main', 'p22'),
    ('cumbia-vip', 'p16'), ('cumbia-vip', 'p17'), ('cumbia-vip', 'p19'),
    ('cumbia-vip', 'p20'), ('cumbia-vip', 'p21'), ('cumbia-vip', 'p22'),
    ('cumbia-vip', 'p23')
ON CONFLICT (bar_id, product_id) DO NOTHING;
